In [1]:
#import
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="darkgrid")
#Read
df = pd.read_csv("train.csv")
#Column names reset
df.columns = ['id', 'surv', 'pcclass', 'name', 'sex', 'age', 'sibsp', 'parch','ticket','fare','cabin', 'embarked']

In [6]:
df.embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [7]:
df.pcclass.unique()

array([3, 1, 2], dtype=int64)

In [51]:
ces = list(df.pcclass)
print(ces.count(3))

491


In [65]:
def demasking_nan (column, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if pd.notnull(e) == True]
    return list(mask_column)

mask_pc3 = masking("pcclass", 3, df) 

mask_cabin_nan = demasking_nan("cabin", df)

mask_cabin_pc3 = mask_merge(mask_pc3, mask_cabin_nan)

cabin_nan_pc3 = df.loc[mask_cabin_pc3]


print(cabin_nan_pc3[["surv", "cabin", "sex", "age", "embarked", "name"]])

     surv  cabin     sex   age embarked  \
10      1     G6  female   4.0        S   
75      0  F G73    male  25.0        S   
128     1  F E69  female   NaN        C   
205     0     G6  female   2.0        S   
251     0     G6  female  29.0        S   
394     1     G6  female  24.0        S   
429     1    E10    male  32.0        S   
699     0  F G63    male  42.0        S   
715     0  F G73    male  19.0        S   
751     1   E121    male   6.0        S   
776     0    F38    male   NaN        Q   
823     1   E121  female  27.0        S   

                                                  name  
10                     Sandstrom, Miss. Marguerite Rut  
75                             Moen, Mr. Sigurd Hansen  
128                                  Peter, Miss. Anna  
205                         Strom, Miss. Telma Matilda  
251         Strom, Mrs. Wilhelm (Elna Matilda Persson)  
394  Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...  
429                 Pickard, Mr. Berk (Be

In [26]:
df.sibsp.unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [27]:
df.parch.unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [40]:
sib_list = list(df.sibsp)
print(sib_list.count(8))
print(sib_list.count(5))
print(sib_list.count(4))
print(sib_list.count(3))
print(sib_list.count(2))
print(sib_list.count(1))
print(sib_list.count(0))

7
5
18
16
28
209
608


In [41]:
par_list = list(df.parch)
print(par_list.count(6))
print(par_list.count(5))
print(par_list.count(4))
print(par_list.count(3))
print(par_list.count(2))
print(par_list.count(1))
print(par_list.count(0))

1
5
4
5
80
118
678


In [42]:
def masking (column, attribute, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if e == attribute]
    return list(mask_column)

def mask_merge(list1, list2):
    merged_mask = []
    for a in list1:
        if a in list2:
            merged_mask.append(a)
    return merged_mask

#conditional survival rate
def con_surv(mask):
    df_new = df.loc[mask]
    con_sur_rate = df_new.surv.sum()/len(list(df_new.surv))
    return con_sur_rate

In [48]:
mask_sing1 = masking("sibsp", 0, df)
mask_sing2 = masking("parch", 0, df)

mask_sing = mask_merge(mask_sing1, mask_sing2)

bes = df.name.loc[mask_sing]


In [70]:
def masking2 (column, attribute, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if e != attribute]
    return list(mask_column)

mask_parch_high = masking2("parch", 0, df)
ves = con_surv(mask_parch_high)
print(ves)

mask_pc1 = masking("pcclass", 1, df)
mask_pc2 = masking("pcclass", 2, df)

m1 = mask_merge(mask_pc1, mask_parch_high)
m2 = mask_merge(mask_pc2, mask_parch_high)
m3 = mask_merge(mask_pc3, mask_parch_high)

zes = con_surv(m1)
des = con_surv(m2)
hes = con_surv(m3)

print(zes)
print(des)
print(hes)

print(len(m1))
print(len(m2))
print(len(m3))



0.5117370892018779
0.6981132075471698
0.78
0.3
53
50
110


In [71]:
mask_sibsp_high = masking2("sibsp", 0, df)
vas = con_surv(mask_sibsp_high)
print(vas)


n1 = mask_merge(mask_pc1, mask_sibsp_high)
n2 = mask_merge(mask_pc2, mask_sibsp_high)
n3 = mask_merge(mask_pc3, mask_sibsp_high)

zas = con_surv(m1)
das = con_surv(m2)
has = con_surv(m3)

print(zas)
print(das)
print(has)

print(len(n1))
print(len(n2))
print(len(n3))

0.4664310954063604
0.6981132075471698
0.78
0.3
79
64
140


In [80]:
def con_fem(mask):
    df_new = df.loc[mask]
    f = list(df_new.sex)
    con_fem_rate = f.count("female")/len(f)
    return con_fem_rate

def con_pcclass(mask, pcclass):
    df_new = df.loc[mask]
    f = list(df_new.pcclass)
    con_pcclass_rate = f.count(pcclass)/len(f)
    return con_pcclass_rate

mask_S = masking ("embarked", "S", df)
mask_C = masking ("embarked", "C", df)
mask_Q = masking ("embarked", "Q", df)

fes1 = con_fem(mask_S)
fes2 = con_fem(mask_C)
fes3 = con_fem(mask_Q)
les11 = con_pcclass(mask_S, 1)
les12 = con_pcclass(mask_S, 2)
les13 = con_pcclass(mask_S, 3)
les21 = con_pcclass(mask_C, 1)
les22 = con_pcclass(mask_C, 2)
les23 = con_pcclass(mask_C, 3)
les31 = con_pcclass(mask_Q, 1)
les32 = con_pcclass(mask_Q, 2)
les33 = con_pcclass(mask_Q, 3)

jes = list(df.embarked)

es1_all=jes.count("S")/(len(jes)-2)
es2_all=jes.count("C")/(len(jes)-2)
es3_all=jes.count("Q")/(len(jes)-2)

print(fes1)
print(fes2)
print(fes3)
print()
print(les11)
print(les12)
print(les13)
print()
print(les21)
print(les22)
print(les23)
print()
print(les31)
print(les31)
print(les33)
print()
print(es1_all)
print(es2_all)
print(es3_all)


0.31521739130434784
0.43452380952380953
0.4675324675324675

0.1972049689440994
0.2546583850931677
0.5481366459627329

0.5059523809523809
0.10119047619047619
0.39285714285714285

0.025974025974025976
0.025974025974025976
0.935064935064935

0.7244094488188977
0.1889763779527559
0.08661417322834646


In [ ]:
0.4351851851851852
0.41304347826086957
0.29327902240325865
1.0
1.0
1.0
0.24242424242424243
0.20650953984287318
0.5510662177328844