In [7]:
#import
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#import plotly as py

sns.set(style="darkgrid")
#Read
df = pd.read_csv("train.csv")
#Column names reset
df.columns = ['id', 'surv', 'pcclass', 'name', 'sex', 'age', 'sibsp', 'parch','ticket','fare','cabin', 'embarked']

In [8]:
df.embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [25]:
df.pcclass.unique()

array([3, 1, 2], dtype=int64)

In [26]:
ces = list(df.pcclass)
print(ces.count(3))

491


In [24]:
def demasking_nan (column, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if pd.notnull(e) == True]
    return list(mask_column)

mask_pc3 = masking("pcclass", 3, df) 

mask_cabin_nan = demasking_nan("cabin", df)

mask_cabin_pc3 = mask_merge(mask_pc3, mask_cabin_nan)

cabin_nan_pc3 = df.loc[mask_cabin_pc3]


print(cabin_nan_pc3[["surv", "cabin", "sex", "age", "embarked", "name"]])

     surv  cabin     sex   age embarked  \
10      1     G6  female   4.0        S   
75      0  F G73    male  25.0        S   
128     1  F E69  female   NaN        C   
205     0     G6  female   2.0        S   
251     0     G6  female  29.0        S   
394     1     G6  female  24.0        S   
429     1    E10    male  32.0        S   
699     0  F G63    male  42.0        S   
715     0  F G73    male  19.0        S   
751     1   E121    male   6.0        S   
776     0    F38    male   NaN        Q   
823     1   E121  female  27.0        S   

                                                  name  
10                     Sandstrom, Miss. Marguerite Rut  
75                             Moen, Mr. Sigurd Hansen  
128                                  Peter, Miss. Anna  
205                         Strom, Miss. Telma Matilda  
251         Strom, Mrs. Wilhelm (Elna Matilda Persson)  
394  Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...  
429                 Pickard, Mr. Berk (Be

In [27]:
df.sibsp.unique()

array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [28]:
df.parch.unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [29]:
sib_list = list(df.sibsp)
print(sib_list.count(8))
print(sib_list.count(5))
print(sib_list.count(4))
print(sib_list.count(3))
print(sib_list.count(2))
print(sib_list.count(1))
print(sib_list.count(0))

7
5
18
16
28
209
608


In [30]:
par_list = list(df.parch)
print(par_list.count(6))
print(par_list.count(5))
print(par_list.count(4))
print(par_list.count(3))
print(par_list.count(2))
print(par_list.count(1))
print(par_list.count(0))

1
5
4
5
80
118
678


In [31]:
def masking (column, attribute, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if e == attribute]
    return list(mask_column)

def mask_merge(list1, list2):
    merged_mask = []
    for a in list1:
        if a in list2:
            merged_mask.append(a)
    return merged_mask

#conditional survival rate
def con_surv(mask):
    df_new = df.loc[mask]
    con_sur_rate = df_new.surv.sum()/len(list(df_new.surv))
    return con_sur_rate

In [32]:
mask_sing1 = masking("sibsp", 0, df)
mask_sing2 = masking("parch", 0, df)

mask_sing = mask_merge(mask_sing1, mask_sing2)

bes = df.name.loc[mask_sing]


In [33]:
def masking2 (column, attribute, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if e != attribute]
    return list(mask_column)

mask_parch_high = masking2("parch", 0, df)
ves = con_surv(mask_parch_high)
print(ves)

mask_pc1 = masking("pcclass", 1, df)
mask_pc2 = masking("pcclass", 2, df)

m1 = mask_merge(mask_pc1, mask_parch_high)
m2 = mask_merge(mask_pc2, mask_parch_high)
m3 = mask_merge(mask_pc3, mask_parch_high)

zes = con_surv(m1)
des = con_surv(m2)
hes = con_surv(m3)

print(zes)
print(des)
print(hes)

print(len(m1))
print(len(m2))
print(len(m3))



0.5117370892018779
0.6981132075471698
0.78
0.3
53
50
110


In [34]:
mask_sibsp_high = masking2("sibsp", 0, df)
vas = con_surv(mask_sibsp_high)
print(vas)


n1 = mask_merge(mask_pc1, mask_sibsp_high)
n2 = mask_merge(mask_pc2, mask_sibsp_high)
n3 = mask_merge(mask_pc3, mask_sibsp_high)

zas = con_surv(m1)
das = con_surv(m2)
has = con_surv(m3)

print(zas)
print(das)
print(has)

print(len(n1))
print(len(n2))
print(len(n3))

0.4664310954063604
0.6981132075471698
0.78
0.3
79
64
140


In [35]:
def con_fem(mask):
    df_new = df.loc[mask]
    f = list(df_new.sex)
    con_fem_rate = f.count("female")/len(f)
    return con_fem_rate

def con_pcclass(mask, pcclass):
    df_new = df.loc[mask]
    f = list(df_new.pcclass)
    con_pcclass_rate = f.count(pcclass)/len(f)
    return con_pcclass_rate

mask_S = masking ("embarked", "S", df)
mask_C = masking ("embarked", "C", df)
mask_Q = masking ("embarked", "Q", df)

fes1 = con_fem(mask_S)
fes2 = con_fem(mask_C)
fes3 = con_fem(mask_Q)
les11 = con_pcclass(mask_S, 1)
les12 = con_pcclass(mask_S, 2)
les13 = con_pcclass(mask_S, 3)
les21 = con_pcclass(mask_C, 1)
les22 = con_pcclass(mask_C, 2)
les23 = con_pcclass(mask_C, 3)
les31 = con_pcclass(mask_Q, 1)
les32 = con_pcclass(mask_Q, 2)
les33 = con_pcclass(mask_Q, 3)

jes = list(df.embarked)

es1_all=jes.count("S")/(len(jes)-2)
es2_all=jes.count("C")/(len(jes)-2)
es3_all=jes.count("Q")/(len(jes)-2)

print(fes1)
print(fes2)
print(fes3)
print()
print(les11)
print(les12)
print(les13)
print()
print(les21)
print(les22)
print(les23)
print()
print(les31)
print(les31)
print(les33)
print()
print(es1_all)
print(es2_all)
print(es3_all)


0.31521739130434784
0.43452380952380953
0.4675324675324675

0.1972049689440994
0.2546583850931677
0.5481366459627329

0.5059523809523809
0.10119047619047619
0.39285714285714285

0.025974025974025976
0.025974025974025976
0.935064935064935

0.7244094488188977
0.1889763779527559
0.08661417322834646


In [ ]:
#masking conditionals
def freq_age_groups(dat1):
    age_0_20 = 0
    age_20_60 = 0 
    age_60 = 0
    for ages in dat1["age"]:
        if ages <= 14:
            age_0_20 += 1
        elif 20 < ages <= 60:
            age_20_60 += 1
        else:
            age_60 += 1
    age_list = [age_0_20, age_20_60 , age_60]        
    return age_list


In [38]:
print(list(df.age))

[22.0, 38.0, 26.0, 35.0, 35.0, nan, 54.0, 2.0, 27.0, 14.0, 4.0, 58.0, 20.0, 39.0, 14.0, 55.0, 2.0, nan, 31.0, nan, 35.0, 34.0, 15.0, 28.0, 8.0, 38.0, nan, 19.0, nan, nan, 40.0, nan, nan, 66.0, 28.0, 42.0, nan, 21.0, 18.0, 14.0, 40.0, 27.0, nan, 3.0, 19.0, nan, nan, nan, nan, 18.0, 7.0, 21.0, 49.0, 29.0, 65.0, nan, 21.0, 28.5, 5.0, 11.0, 22.0, 38.0, 45.0, 4.0, nan, nan, 29.0, 19.0, 17.0, 26.0, 32.0, 16.0, 21.0, 26.0, 32.0, 25.0, nan, nan, 0.83, 30.0, 22.0, 29.0, nan, 28.0, 17.0, 33.0, 16.0, nan, 23.0, 24.0, 29.0, 20.0, 46.0, 26.0, 59.0, nan, 71.0, 23.0, 34.0, 34.0, 28.0, nan, 21.0, 33.0, 37.0, 28.0, 21.0, nan, 38.0, nan, 47.0, 14.5, 22.0, 20.0, 17.0, 21.0, 70.5, 29.0, 24.0, 2.0, 21.0, nan, 32.5, 32.5, 54.0, 12.0, nan, 24.0, nan, 45.0, 33.0, 20.0, 47.0, 29.0, 25.0, 23.0, 19.0, 37.0, 16.0, 24.0, nan, 22.0, 24.0, 19.0, 18.0, 19.0, 27.0, 9.0, 36.5, 42.0, 51.0, 22.0, 55.5, 40.5, nan, 51.0, 16.0, 30.0, nan, nan, 44.0, 40.0, 26.0, 17.0, 1.0, 9.0, nan, 45.0, nan, 28.0, 61.0, 4.0, 1.0, 21.0, 56.

In [40]:
def masking3(column, attribute1, attribute2, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if attribute1 <= e < attribute2]
    return list(mask_column)


def masking2 (column, attribute, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if e != attribute]
    return list(mask_column)

In [41]:
mask_age_0_15 = masking3("age", 0 , 15, df)
mask_age_15_20 = masking3("age", 15 , 20, df)
mask_age_20_40 = masking3("age", 20 , 40, df)
mask_age_40_100 = masking3("age", 40, 100, df)

In [43]:
surv_rate_age_0_15 = con_surv(mask_age_0_15)
surv_rate_age_15_20 = con_surv(mask_age_15_20)
surv_rate_age_20_40 = con_surv(mask_age_20_40)
surv_rate_age_40_100 = con_surv(mask_age_40_100)
print(surv_rate_age_0_15)
print(surv_rate_age_15_20)
print(surv_rate_age_20_40)
print(surv_rate_age_40_100)

0.5769230769230769
0.3953488372093023
0.3875968992248062
0.37423312883435583


In [44]:
survival_rate = df.surv.sum()/len(df.surv)
print(survival_rate)

0.3838383838383838


In [83]:
def con_surv(mask):
    df_new = df.loc[mask]
    con_sur_rate = df_new.surv.sum()/len(list(df_new.surv))
    return con_sur_rate

def mask_3_merge(mask1, mask2, mask3):
    merged_mask1 = []
    merged_mask2 = []
    for a in mask1:
        if a in mask2:
            merged_mask1.append(a)
    for b in merged_mask1:
        if b in mask3:
            merged_mask2.append(b)
    return con_surv(merged_mask2)

def masking3(column, attribute1, attribute2, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if attribute1 <= e < attribute2]
    return list(mask_column)

def masking_cat(column, attribute1, attribute2, dataframe):
    a= dataframe[column]
    mask_column = [i for i, e in enumerate(list(a)) if attribute1 <= e < attribute2]
    return list(mask_column)

In [133]:
#mask1: "male", "female"
#mask2: "1", "2", "3"
#mask3: "Age between 0, 15", "Age between 0, 15","Age between 0, 15", "Age between 0, 15"

def inner_1(row_index):
        if str(df.loc[row_index].sex) == "male":
            mask_1 = mask_male
        else:
            mask_1 = mask_fem
        return mask_1

    
def inner_2(row_index):
        if df.loc[row_index].pcclass == 1:
            mask_2 = mask_pc1
        elif df.loc[row_index].pcclass == 2:
            mask_2 = mask_pc2
        else:
            mask_2 = mask_pc3
        return mask_2
    
def inner_3(row_index):
        if 0 <= float(df.loc[row_index].age) < 15 :
            mask_3 = mask_age_0_15
        elif 15 <= float(df.loc[row_index].age) < 20:
            mask_3 = mask_age_15_20
        elif 20 <= float(df.loc[row_index].age) < 40:
            mask_3 = mask_age_20_40
        elif 40 <= float(df.loc[row_index].age) < 100:
                mask_3 = mask_age_40_100
        else:
            mask_3 = list(df.index)
        return mask_3
    
    





def iterater(list_index):
    iterated_list = []
    for i in list_index:
        iterated_list.append(mask_3_merge(inner_1(i), inner_2(i), inner_3(i)))
    return iterated_list

list_of_indices = list(df.index)

pred_surv_rates = pd.DataFrame(iterater(list_of_indices))

df["prediction1"] = pred_surv_rates

print(df.head())
    

   id  surv  pcclass                                               name  \
0   1     0        3                            Braund, Mr. Owen Harris   
1   2     1        1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2   3     1        3                             Heikkinen, Miss. Laina   
3   4     1        1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4   5     0        3                           Allen, Mr. William Henry   

      sex   age  sibsp  parch            ticket     fare cabin embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   prediction1  
0     0.154839  
1     0.976744  
2     0.468085  
3     0.976744  
4     0.15483

In [118]:
mask_fem = masking ("sex", "female", df)
mask_male = masking ("sex", "male", df)

In [119]:
mask_pc1 = masking("pcclass", 1, df) 
mask_pc2 = masking("pcclass", 2, df) 
mask_pc3 = masking("pcclass", 3, df) 

In [120]:
mask_age_0_15 = masking_cat("age", 0 , 15, df)
mask_age_15_20 = masking_cat("age", 15 , 20, df)
mask_age_20_40 = masking_cat("age", 20 , 40, df)
mask_age_40_100 = masking_cat("age", 40, 100, df)

In [60]:
print(int(df.loc[1].pcclass))

1


In [109]:
df.loc[4].pcclass == 3

True

In [64]:
print(int(df.index))


TypeError: int() argument must be a string, a bytes-like object or a number, not 'RangeIndex'

In [100]:
df.loc[1].pcclass

1